### ISSUE TITLE
Logout URL: Mixed content when using HTTPS in frontend and HTTP for API communication

### ISSUE THREAD

**Issue by mjansenDatabay** [DatabayAG/ILIAS_AdobeConnectPlugin#16]
I suggest to change the logout URL built in `./classes/class.ilObjAdobeConnectGUI.php`
`$sso_tpl->setVariable('LOGOUT_URL', str_replace(['http://', 'https://'], '//', $logout_url));`

**Comment by playamongthestars** [comment]
Fixed for releases: 3, 4, 5
