### ISSUE TITLE
fatal error when opening "ILIAS-Settings"

### ISSUE THREAD

**Issue by theodortruffer** [DatabayAG/ILIAS_AdobeConnectPlugin#17]
Hello!
I just installed installed release_4_1_x on an ILIAS v5.2.14. Inside the plugin configuration, when I click on the tab "ILIAS-Settings" I receive the following error:

ilErrorHandling::{closure}:50 2 Invalid argument supplied for foreach() in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/AdobeConnect/classes/class.ilAdobeConnectXMLAPI.php:2082

**Comment by mjansenDatabay** [comment]
@nmatuschek Please add some more result checks before operating on potentially available ```SimpleXmlElement``` properties.

**Comment by playamongthestars** [comment]
I committed a bugfix. This issue should be fixed. Could you please give me a feedback if this fix solves your issue? Thank you
