### ISSUE TITLE
"The Adobe Connect meeting-folder is not available"

### ISSUE THREAD

**Issue by davideOCGROUP** [DatabayAG/ILIAS_AdobeConnectPlugin#7]
Hi,
I'm trying to connect my AdobeConnect account to our ILIAS platform but when i try to create a new course i obtain this error? What does it mean? My Administrator account is in Meeting Host Group..
Thanks a lot

**Comment by playamongthestars** [comment]
The message  “The Adobe Connect meeting-folder is not available” is shown in case there is no existing meeting-folder-id at the Adobe Connect Server. The reason for this could be, that the account you entered in the Adobe-Settings of the plugin doesn't have the permission to create meetings. 

Another reason could be, that it was not possible to find a valid account on the Adobe Connect Server. 
If you have access to the database of the ILIAS installation search the table 'rep_robj_xavc_users' and delete the entry wihich contains your "xavc_login". After that, delete all cookies within your browser and try again to create a room.

**Comment by playamongthestars** [comment]
By the way ... are you using a proxy?

**Comment by davideOCGROUP** [comment]
I have tried both of two authentication options in two different servers: one behind a proxy and another directly connected on internet. Then i try to create a meeting in a my AdConnect interface but when i try to add a meeting (through the repository adding list) i obtain the same error. I haven't tried your DB workaround because i haven't the DB access. Are there any other explanation? Thanks you very much?

**Comment by playamongthestars** [comment]
This Adobe Connect-Plugin does not support the use of a proxy. What exactly do you mean with two different authentification options? I guess with  "AdConnect interface" you mean the Adobe Connect server itself? 
Are you able to create a room on the Adobe Connect Server without using the ILIAS-Plugin?  
Do you have a Tab "My Meetings" at the Adobe Connect Server? 
![adobe_connect_server](https://cloud.githubusercontent.com/assets/2510394/24545489/a20cfaa0-1607-11e7-8664-7caef65678ff.png)

**Comment by davideOCGROUP** [comment]
As you can see after i made a meeting on adobe server and i try to link it on the plugin interface under "adobe connect/create adobe meeting" it show me what you can see in the second picture. 
At last, in AdConnect plugin administrative interface, i have set the following "registration mode" is it correct? or i have to do another configuration? 

![schermata 2017-04-18 alle 13 04 18](https://cloud.githubusercontent.com/assets/26787692/25127883/e57475c8-2437-11e7-8243-610dca409f21.png)
![schermata 2017-04-18 alle 13 04 28](https://cloud.githubusercontent.com/assets/26787692/25127884/e588e030-2437-11e7-8e2c-c46e4176de68.png)
![schermata 2017-04-18 alle 13 05 57](https://cloud.githubusercontent.com/assets/26787692/25127885/e5981546-2437-11e7-8d01-0a029fc88313.png)

**Comment by davideOCGROUP** [comment]
And here you can say my DB entries when i try to create a new meeting but the email is different from what i use in adobe server
![schermata 2017-04-18 alle 13 13 32](https://cloud.githubusercontent.com/assets/26787692/25128135/dbdaa5b8-2438-11e7-8ed6-7bd62543b21a.png)

**Comment by playamongthestars** [comment]
Ok. If you want to "reuse" an Adobe Connect meeting room which is already exists on the AC-Server it works a bit different.  
First you need to activate setting for the extended creation form. You can find it here: 
![01_enable_settings](https://cloud.githubusercontent.com/assets/2510394/25174002/511685fa-24f6-11e7-9ddc-640aa151b8a0.png)

Now create a new Adobe Connect Meeting object in ILIAS and select the extended section. 
![02_create_meeting](https://cloud.githubusercontent.com/assets/2510394/25174085/90c1a0cc-24f6-11e7-80ee-66afd376717d.png)

Klick "Reuse an existing Adobe Connect Meeting" and select a room. 
If there is no meeting room list check the settings of the entered Adobe Login in the Plugin Administration. 
Most important: It musst be the same Account you use for creating meeting room at the Adobe Connect Server directly! (Not the account with the number at the beginning!)  

![03_adobe_admin_login](https://cloud.githubusercontent.com/assets/2510394/25174224/fa6591c8-24f6-11e7-9156-742b31783548.png)
