### ISSUE TITLE
Document Upload in ILIAS-Meetingroom fails without error message

### ISSUE THREAD

**Issue by fheibel** [DatabayAG/ILIAS_AdobeConnectPlugin#8]
Hi, uploading files in ILIAS-Meetingroom fails: Add new file -> Select file -> Open -> Save -> message in green appears on top: "Adobe Meeting content added" But unfortunately there are no files at all.
After Entering Adobe Meeting file-upload works without failure. Files uploaded from within the Adobe Meeting itself do appear within ILIAS-Meetingroom correctly.
ILIAS (v5.2.2)

Thanks for your support

**Comment by frankheibel** [comment]
Hi there is an other issue with "Start date of the Adobe Meeting": I can't change existing start dates of existing Meetings any more. It's also impossible to create new meetings with fixed date starting in future. Datepicker let's select dates but it's not possible to save it.
At this moment we are only able to crate new meetings with "permanent open room".

Thanks for your help

**Comment by fheibel** [comment]
Sorry I closed the issue accidentally.

**Comment by bogenschlag** [comment]
While this is inconvenient, I consider [Creating new Meetings fails with fixed start date fails](https://github.com/DatabayAG/ILIAS_AdobeConnectPlugin/issues/9) to be the (much) bigger problem.

**Comment by mjansenDatabay** [comment]
Yesterday I could reproduce this issue. But as I checked my AC object in ILIAS today, the file uploaded yesterday is now visible. Maybe a huge delay when using the API to upload to and read files from the AC server... I will perform some more checks...

**Comment by mjansenDatabay** [comment]
I added some logging, maybe this helps to identify the issue. When using the AdobeConnect DFN API I always get:
```xml
<status code="invalid"><invalid field="file" type="string" subcode="format"/></status>
```

**Comment by fheibel** [comment]
Hi, th issue still exists. Adding a simple PDF-File seems to work *without* eror-message: "Inhalt hinzugefügt"
But there is no file visible.

**Comment by mjansenDatabay** [comment]
I commited a CURL related fix which solves this issue (at least on my local installation).

Please check your ILIAS log file if you still can't upload files and provide the respective log lines.
